@api = http://localhost:3000/products

### get all products
GET {{api}}

### create a product
POST {{api}}
Content-Type: application/json

{
    "title": "Product 2",
    "description": "This is a product",
    "price": "100.00",
    "image": "http://www.example.com/image.jpg",
    "quantity": "10"
}

### get a single product by id
GET {{api}}/614668fa6a148afa452187c2

### update a product by id
PUT {{api}}/614668fa6a148afa452187c2
Content-Type: application/json

{
    "title": "Product 2",
    "description": "a second product",
    "price": "120.00"
}

### delete a product by id
DELETE {{api}}/614668d7a08cdcea8b77ced6